console.log(process.env)

const log = {
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\admin\\AppData\\Roaming',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-9OJO1FB',
    ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\admin',
    LANG: 'en_US.UTF-8',
    LOCALAPPDATA: 'C:\\Users\\admin\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-9OJO1FB',
    NUMBER_OF_PROCESSORS: '8',
    OneDrive: 'C:\\Users\\admin\\OneDrive',
    OS: 'Windows_NT',
    Path: 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Windows\\System32;C:\\Users\\admin\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\admin\\AppData\\Roaming\\npm',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '8e0a',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Users\\admin\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\WINDOWS',
    TEMP: 'C:\\Users\\admin\\AppData\\Local\\Temp',
    TERM_PROGRAM: 'vscode',
    TERM_PROGRAM_VERSION: '1.25.1',
    TMP: 'C:\\Users\\admin\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-9OJO1FB',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-9OJO1FB',
    USERNAME: 'admin',
    USERPROFILE: 'C:\\Users\\admin',
    VSCODE_CWD: 'C:\\WINDOWS\\system32',
    VSCODE_IPC_HOOK: '\\\\.\\pipe\\40c024692924a7e0e09c00bf44e8c2ef-1.25.1-main-sock',
    VSCODE_NLS_CONFIG: '{"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"b2a999fc509c8bbe09c27e781d92b27e.zh-cn","_translationsConfigFile":"C:\\\\Users\\\\admin\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\b2a999fc509c8bbe09c27e781d92b27e.zh-cn\\\\tcf.json","_cacheRoot":"C:\\\\Users\\\\admin\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\b2a999fc509c8bbe09c27e781d92b27e.zh-cn","_resolvedLanguagePackCoreLocation":"C:\\\\Users\\\\admin\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\b2a999fc509c8bbe09c27e781d92b27e.zh-cn\\\\1dfc5e557209371715f655691b1235b6b26a06be"}',
    VSCODE_NODE_CACHED_DATA_DIR_5924: 'C:\\Users\\admin\\AppData\\Roaming\\Code\\CachedData\\1dfc5e557209371715f655691b1235b6b26a06be',
    VSCODE_PID: '5924',
    windir: 'C:\\WINDOWS'
}